



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
module App {
    
    /**
     * Interface for: _99meat.Models.AudienceModel
     */
     export interface IAudienceModel {
        
        Name: string;
    }
 
    /**
     * Base view model for _99meat.Models.AudienceModel
     */
    export class AudienceModel  implements IAudienceModel  {
         
       public Name: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.AddExternalLoginBindingModel
     */
     export interface IAddExternalLoginBindingModel {
        
        ExternalAccessToken: string;
    }
 
    /**
     * Base view model for _99meat.Models.AddExternalLoginBindingModel
     */
    export class AddExternalLoginBindingModel  implements IAddExternalLoginBindingModel  {
         
       public ExternalAccessToken: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.ChangeResetPasswordBindingModel
     */
     export interface IChangeResetPasswordBindingModel {
        
        Token: string;
        Email: string;
        NewPassword: string;
        ConfirmPassword: string;
    }
 
    /**
     * Base view model for _99meat.Models.ChangeResetPasswordBindingModel
     */
    export class ChangeResetPasswordBindingModel  implements IChangeResetPasswordBindingModel  {
         
       public Token: string;
       public Email: string;
       public NewPassword: string;
       public ConfirmPassword: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.ChangePasswordBindingModel
     */
     export interface IChangePasswordBindingModel {
        
        OldPassword: string;
        NewPassword: string;
        ConfirmPassword: string;
    }
 
    /**
     * Base view model for _99meat.Models.ChangePasswordBindingModel
     */
    export class ChangePasswordBindingModel  implements IChangePasswordBindingModel  {
         
       public OldPassword: string;
       public NewPassword: string;
       public ConfirmPassword: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.RegisterBindingModel
     */
     export interface IRegisterBindingModel {
        
        Email: string;
        Password: string;
        ConfirmPassword: string;
        PhoneNumber: string;
        FirstName: string;
        LastName: string;
    }
 
    /**
     * Base view model for _99meat.Models.RegisterBindingModel
     */
    export class RegisterBindingModel  implements IRegisterBindingModel  {
         
       public Email: string;
       public Password: string;
       public ConfirmPassword: string;
       public PhoneNumber: string;
       public FirstName: string;
       public LastName: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.RegisterExternalBindingModel
     */
     export interface IRegisterExternalBindingModel {
        
        Email: string;
    }
 
    /**
     * Base view model for _99meat.Models.RegisterExternalBindingModel
     */
    export class RegisterExternalBindingModel  implements IRegisterExternalBindingModel  {
         
       public Email: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.RemoveLoginBindingModel
     */
     export interface IRemoveLoginBindingModel {
        
        LoginProvider: string;
        ProviderKey: string;
    }
 
    /**
     * Base view model for _99meat.Models.RemoveLoginBindingModel
     */
    export class RemoveLoginBindingModel  implements IRemoveLoginBindingModel  {
         
       public LoginProvider: string;
       public ProviderKey: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.SetPasswordBindingModel
     */
     export interface ISetPasswordBindingModel {
        
        NewPassword: string;
        ConfirmPassword: string;
    }
 
    /**
     * Base view model for _99meat.Models.SetPasswordBindingModel
     */
    export class SetPasswordBindingModel  implements ISetPasswordBindingModel  {
         
       public NewPassword: string;
       public ConfirmPassword: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}