



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
module App {
    
    /**
     * Interface for: _99meat.Models.ExternalLoginViewModel
     */
     export interface IExternalLoginViewModel {
        
        Name: string;
        Url: string;
        State: string;
    }
 
    /**
     * Base view model for _99meat.Models.ExternalLoginViewModel
     */
    export class ExternalLoginViewModel  implements IExternalLoginViewModel  {
         
       public Name: string;
       public Url: string;
       public State: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.ManageInfoViewModel
     */
     export interface IManageInfoViewModel {
        
        LocalLoginProvider: string;
        Email: string;
        Logins: UserLoginInfoViewModel[];
        ExternalLoginProviders: ExternalLoginViewModel[];
    }
 
    /**
     * Base view model for _99meat.Models.ManageInfoViewModel
     */
    export class ManageInfoViewModel  implements IManageInfoViewModel  {
         
       public LocalLoginProvider: string;
       public Email: string;
       public Logins: UserLoginInfoViewModel[];
       public ExternalLoginProviders: ExternalLoginViewModel[];  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.UserInfoViewModel
     */
     export interface IUserInfoViewModel {
        
        Id: string;
        Email: string;
        HasRegistered: boolean;
        LoginProvider: string;
    }
 
    /**
     * Base view model for _99meat.Models.UserInfoViewModel
     */
    export class UserInfoViewModel  implements IUserInfoViewModel  {
         
       public Id: string;
       public Email: string;
       public HasRegistered: boolean;
       public LoginProvider: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.Models.UserLoginInfoViewModel
     */
     export interface IUserLoginInfoViewModel {
        
        LoginProvider: string;
        ProviderKey: string;
    }
 
    /**
     * Base view model for _99meat.Models.UserLoginInfoViewModel
     */
    export class UserLoginInfoViewModel  implements IUserLoginInfoViewModel  {
         
       public LoginProvider: string;
       public ProviderKey: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}