//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
var App;
(function (App) {
    /**
     * Base view model for _99meat.Models.ExternalLoginViewModel
     */
    var ExternalLoginViewModel = (function () {
        function ExternalLoginViewModel() {
            //nothing                   
        }
        return ExternalLoginViewModel;
    }());
    App.ExternalLoginViewModel = ExternalLoginViewModel;
    /**
     * Base view model for _99meat.Models.ManageInfoViewModel
     */
    var ManageInfoViewModel = (function () {
        function ManageInfoViewModel() {
            //nothing                   
        }
        return ManageInfoViewModel;
    }());
    App.ManageInfoViewModel = ManageInfoViewModel;
    /**
     * Base view model for _99meat.Models.UserInfoViewModel
     */
    var UserInfoViewModel = (function () {
        function UserInfoViewModel() {
            //nothing                   
        }
        return UserInfoViewModel;
    }());
    App.UserInfoViewModel = UserInfoViewModel;
    /**
     * Base view model for _99meat.Models.UserLoginInfoViewModel
     */
    var UserLoginInfoViewModel = (function () {
        function UserLoginInfoViewModel() {
            //nothing                   
        }
        return UserLoginInfoViewModel;
    }());
    App.UserLoginInfoViewModel = UserLoginInfoViewModel;
})(App || (App = {}));
//# sourceMappingURL=AccountViewModels.js.map