//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
var App;
(function (App) {
    /**
     * Base view model for _99meat.Models.AudienceModel
     */
    var AudienceModel = (function () {
        function AudienceModel() {
            //nothing                   
        }
        return AudienceModel;
    }());
    App.AudienceModel = AudienceModel;
    /**
     * Base view model for _99meat.Models.AddExternalLoginBindingModel
     */
    var AddExternalLoginBindingModel = (function () {
        function AddExternalLoginBindingModel() {
            //nothing                   
        }
        return AddExternalLoginBindingModel;
    }());
    App.AddExternalLoginBindingModel = AddExternalLoginBindingModel;
    /**
     * Base view model for _99meat.Models.ChangeResetPasswordBindingModel
     */
    var ChangeResetPasswordBindingModel = (function () {
        function ChangeResetPasswordBindingModel() {
            //nothing                   
        }
        return ChangeResetPasswordBindingModel;
    }());
    App.ChangeResetPasswordBindingModel = ChangeResetPasswordBindingModel;
    /**
     * Base view model for _99meat.Models.ChangePasswordBindingModel
     */
    var ChangePasswordBindingModel = (function () {
        function ChangePasswordBindingModel() {
            //nothing                   
        }
        return ChangePasswordBindingModel;
    }());
    App.ChangePasswordBindingModel = ChangePasswordBindingModel;
    /**
     * Base view model for _99meat.Models.RegisterBindingModel
     */
    var RegisterBindingModel = (function () {
        function RegisterBindingModel() {
            //nothing                   
        }
        return RegisterBindingModel;
    }());
    App.RegisterBindingModel = RegisterBindingModel;
    /**
     * Base view model for _99meat.Models.RegisterExternalBindingModel
     */
    var RegisterExternalBindingModel = (function () {
        function RegisterExternalBindingModel() {
            //nothing                   
        }
        return RegisterExternalBindingModel;
    }());
    App.RegisterExternalBindingModel = RegisterExternalBindingModel;
    /**
     * Base view model for _99meat.Models.RemoveLoginBindingModel
     */
    var RemoveLoginBindingModel = (function () {
        function RemoveLoginBindingModel() {
            //nothing                   
        }
        return RemoveLoginBindingModel;
    }());
    App.RemoveLoginBindingModel = RemoveLoginBindingModel;
    /**
     * Base view model for _99meat.Models.SetPasswordBindingModel
     */
    var SetPasswordBindingModel = (function () {
        function SetPasswordBindingModel() {
            //nothing                   
        }
        return SetPasswordBindingModel;
    }());
    App.SetPasswordBindingModel = SetPasswordBindingModel;
})(App || (App = {}));
//# sourceMappingURL=AccountBindingModels.js.map