



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
module App {
    
    /**
     * Interface for: _99meat.ViewModel.OrderViewModel
     */
     export interface IOrderViewModel {
        
        Id: number;
        ProdcutName: string;
        OrderDate: Date;
        DeliveryTime: string;
        AddressId: string;
        OrderTotal: number;
        UserId: string;
        OrderStatus: string;
        thumb: string;
    }
 
    /**
     * Base view model for _99meat.ViewModel.OrderViewModel
     */
    export class OrderViewModel  implements IOrderViewModel  {
         
       public Id: number;
       public ProdcutName: string;
       public OrderDate: Date;
       public DeliveryTime: string;
       public AddressId: string;
       public OrderTotal: number;
       public UserId: string;
       public OrderStatus: string;
       public thumb: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.ViewModel.UserOrderViewModel
     */
     export interface IUserOrderViewModel {
        
        Email: string;
        Name: string;
        Total: number;
        PaymentMethod: string;
        OrderAddress: string;
        OrderStatus: string;
        OrderId: number;
        Payment: string;
    }
 
    /**
     * Base view model for _99meat.ViewModel.UserOrderViewModel
     */
    export class UserOrderViewModel  implements IUserOrderViewModel  {
         
       public Email: string;
       public Name: string;
       public Total: number;
       public PaymentMethod: string;
       public OrderAddress: string;
       public OrderStatus: string;
       public OrderId: number;
       public Payment: string;  
 
        constructor() {         
          //nothing                   
        }
    }
    /**
     * Interface for: _99meat.ViewModel.UserOrderDetailViewModel
     */
     export interface IUserOrderDetailViewModel {
        
        ProductName: string;
        Quantity: number;
        UnitPrice: number;
        ProductAmount: number;
        AddressId: string;
        pic: string;
        SpicyLevel: number;
        Instructions: string;
    }
 
    /**
     * Base view model for _99meat.ViewModel.UserOrderDetailViewModel
     */
    export class UserOrderDetailViewModel  implements IUserOrderDetailViewModel  {
         
       public ProductName: string;
       public Quantity: number;
       public UnitPrice: number;
       public ProductAmount: number;
       public AddressId: string;
       public pic: string;
       public SpicyLevel: number;
       public Instructions: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}