//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
var App;
(function (App) {
    /**
     * Base view model for _99meat.ViewModel.OrderViewModel
     */
    var OrderViewModel = (function () {
        function OrderViewModel() {
            //nothing                   
        }
        return OrderViewModel;
    }());
    App.OrderViewModel = OrderViewModel;
    /**
     * Base view model for _99meat.ViewModel.UserOrderViewModel
     */
    var UserOrderViewModel = (function () {
        function UserOrderViewModel() {
            //nothing                   
        }
        return UserOrderViewModel;
    }());
    App.UserOrderViewModel = UserOrderViewModel;
    /**
     * Base view model for _99meat.ViewModel.UserOrderDetailViewModel
     */
    var UserOrderDetailViewModel = (function () {
        function UserOrderDetailViewModel() {
            //nothing                   
        }
        return UserOrderDetailViewModel;
    }());
    App.UserOrderDetailViewModel = UserOrderDetailViewModel;
})(App || (App = {}));
//# sourceMappingURL=Order.js.map